### ISSUE TITLE
所以之前是发生了啥？

### ISSUE THREAD

**Issue by lyimoexiao** [Dress-Collection/Dress#18]
之前还看到项目还在的。。
一下子就不见了？？

**Comment by BBleae** [comment]
原项目 owner 因为个人原因不想维护下去，于是把项目删了。

**Comment by lyimoexiao** [comment]
啊这，那确实太可惜了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月1日(周六) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dress-Collection/Dress] 所以之前是发生了啥？ (Issue #18)




 
原项目 owner 因为个人原因不想维护下去，于是把项目删了。
